# Example configuration for mol_frame
# for the automatic loading of resources.
# This is optional, mol_frame also works without it...

# On Linux, put in $HOME/.config/mol_frame/config.yaml
# On Windows, put in $HOME/mol_frame/config.yaml
# ----------------------------------------------------------------------------
Paths:
    SmilesPath: xxx_smiles_b64.tsv    # tab-delim.
    SmilesCols:
        - Compound_Id
        - Smiles
    StructCols:
        - Compound_Id
        - Smiles
        - Mol_b64
    BatchPath: xxx_batch_data.tsv          # tab-delim.
    BatchCols: []
    ContainerPath: xxx_container.tsv    # tab-delim.
    ContainerCols: []
    # tab-delim.
    ContainerDataPath: xxx_container_data.tsv
    ContainerDataCols: []
